name: Continuous Integration

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.build.outputs.artifacts }}
      version: ${{ steps.check_version.outputs.version }}
      is_snapshot: ${{ steps.check_version.outputs.is_snapshot }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'corretto'
      - name: Build project
        shell: bash
        run: ./mvnw clean install
      - name: Upload target directories as artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: "sample-app"
          path: "./**/target/*"
          retention-days: 4

  integration_tests:
    name: Integration Tests
    needs: [build]
    uses: ./.github/workflows/ci-integration-tests.yml
    secrets: inherit

  publish:
    name: Publish
    needs: [build, integration_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: sample-app
          path: ./
  #      - name: Publish -> a step that could publish our app to an artifact management system (Nexus, JFrog,...)

  evaluate-checks:
    runs-on: ubuntu-latest
    if: always()
    name: Evaluate checks
    needs: [ build, integration_tests, publish ]
    steps:
      - name: Check if all jobs have parsed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: publish